# Generated by Django 6.0.4 on 2026-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TripPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                (
                    "thread_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=200)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("days", models.PositiveIntegerField(blank=True, null=True)),
                ("interests", models.TextField(blank=True)),
                ("travel_type", models.CharField(blank=True, max_length=50)),
                ("ai_draft", models.TextField(blank=True)),
                ("final_itinerary", models.TextField(blank=True)),
                ("user_feedback", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COLLECTING", "Collecting Info"),
                            ("DRAFT", "Draft Ready"),
                            ("APPROVED", "Approved"),
                            ("FAILED", "Failed"),
                        ],
                        default="COLLECTING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
